### ISSUE TITLE
Fat File system support for larger memory IC's

### ISSUE THREAD

**Issue by karimulla1993** [lllucius/esp32_fatflash#2]
Hi,

I am using TC58CVG1S3HxAIx Nand flash from Toshiba. It has an memory size of 2GiB i.e 256MB. I have modified your extFlash code for this flash and everything is working fine from external flash point of view.
Only thing is that these high memory IC's doesn't have sector specific commands such as sector erase and contain erase operations in size of block which is 128KB ,64 times the size of Page. Hence I will not be able to use your code as WL_Flash() class and other lower level drivers are looking for sector erase and chip erase functions

Is their a file system component for esp32 to handle high memory devices.

Thanks,
Karim

**Comment by lllucius** [comment]
Hi Karim,

I too have a chip that doesn't have the typical 4k sector and a played with it a bit to see how to get around the "issue".  What I came up with ONLY works if you have additional PSRAM since it reads the full 128K sector into a buffer (thus the need for PSRAM), updates the buffer as needed with 4k sectors, erases the full 128K sector, and rewrites the full 128K sector.

Not the best solution due to the extra RAM requirements, but I believe it's the only way around it.

**Comment by karimulla1993** [comment]
Ok Thanks, Will Try it
